# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageload',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
