# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_from', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_user_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_user_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '关注用户管理',
                'verbose_name_plural': '关注用户管理',
                'ordering': ('follow_time',),
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100)),
                ('SUC_code', models.CharField(blank=True, max_length=18, null=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('aboutme', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息管理',
                'verbose_name_plural': '用户信息管理',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=2)),
                ('company_or_person', models.CharField(choices=[('企业', '企业'), ('个人', '个人')], default='个人', max_length=2)),
                ('user_ip', models.CharField(max_length=18, null=True)),
                ('last_article_id', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
