# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ID_card',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
