# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='SUC_code_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='SUC_code',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
