# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171211_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ID_card',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
    ]
