# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171214_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='SUC_code_flag',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_or_person',
            field=models.CharField(choices=[(1, '企业'), (2, '个人')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[(1, '男'), (2, '女')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='SUC_code',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
