# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='ImgCrop/images/user/%Y/%m/%d'),
        ),
    ]
