# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171214_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_or_person',
            field=models.CharField(choices=[('企业', '企业'), ('个人', '个人')], default='个人', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=2),
        ),
    ]
