# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180122_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='ImgCrop/images/%Y/%m/%d'),
        ),
    ]
