# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='SUC_code',
            field=models.CharField(blank=True, max_length=18, unique=True),
        ),
    ]
