# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userprofile_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_article_id',
            field=models.IntegerField(null=True),
        ),
    ]
