# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_userprofile_last_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='follow_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
