# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_userinfo_follow_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('follow_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-follow_time',),
            },
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='follow_user',
        ),
    ]
