# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180102_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='follow_user',
        ),
    ]
