# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0012_remove_userinfo_follow_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateField(auto_now_add=True, verbose_name='关注日期')),
                ('follow_user', models.ManyToManyField(blank=True, related_name='follow_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('follow_time',),
            },
        ),
    ]
