# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0013_followuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followuser',
            options={'ordering': ('follow_time',), 'verbose_name': '关注用户管理', 'verbose_name_plural': '关注用户管理'},
        ),
        migrations.RemoveField(
            model_name='followuser',
            name='follow_user',
        ),
        migrations.AddField(
            model_name='followuser',
            name='user_from',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_user_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuser',
            name='user_to',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_user_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='follow_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
