# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('-created',), 'verbose_name': '用户动作管理', 'verbose_name_plural': '用户动作管理'},
        ),
        migrations.AlterField(
            model_name='action',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='动作创建时间'),
        ),
        migrations.AlterField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(max_length=255, verbose_name='用户动作'),
        ),
    ]
