# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 09:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AriticlePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('slug', models.SlugField(max_length=500, verbose_name='段塞')),
                ('body', models.TextField(verbose_name='文章内容')),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 12, 18, 9, 54, 12, 316423), verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AlterModelOptions(
            name='ariticlecolumn',
            options={'verbose_name': '栏目管理', 'verbose_name_plural': '栏目管理'},
        ),
        migrations.AlterField(
            model_name='ariticlecolumn',
            name='column',
            field=models.CharField(max_length=200, verbose_name='栏目'),
        ),
        migrations.AlterField(
            model_name='ariticlecolumn',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='ariticlecolumn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_column', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='ariticlepost',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_column', to='article.AriticleColumn', verbose_name='栏目标题ID'),
        ),
        migrations.AlterIndexTogether(
            name='ariticlepost',
            index_together=set([('id', 'slug')]),
        ),
    ]
