# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171218_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ariticlepost',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterField(
            model_name='ariticlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 19, 38, 28, 852941), verbose_name='创建日期'),
        ),
    ]
