# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171218_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ariticlecolumn',
            options={'verbose_name': '话题标签管理', 'verbose_name_plural': '话题标签管理'},
        ),
        migrations.AlterField(
            model_name='ariticlecolumn',
            name='column',
            field=models.CharField(max_length=200, verbose_name='话题标签名称'),
        ),
        migrations.AlterField(
            model_name='ariticlepost',
            name='body',
            field=models.TextField(verbose_name='话题内容'),
        ),
        migrations.AlterField(
            model_name='ariticlepost',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_column', to='article.AriticleColumn', verbose_name='话题标签名称'),
        ),
        migrations.AlterField(
            model_name='ariticlepost',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='ariticlepost',
            name='slug',
            field=models.SlugField(max_length=500, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='ariticlepost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='话题名称'),
        ),
    ]
