# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_ariticlepost_user_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ariticlepost',
            old_name='user_like',
            new_name='users_like',
        ),
    ]
