# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_comment_is_best_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_best_answer',
        ),
    ]
