# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0009_remove_comment_is_best_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=24, verbose_name='问题标签')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
        ),
        migrations.AlterModelOptions(
            name='ariticlecolumn',
            options={'verbose_name': '私有栏目管理', 'verbose_name_plural': '私有栏目管理'},
        ),
        migrations.AlterField(
            model_name='ariticlecolumn',
            name='column',
            field=models.CharField(max_length=200, verbose_name='私有栏目名称'),
        ),
        migrations.AlterField(
            model_name='ariticlepost',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_column', to='article.AriticleColumn', verbose_name='话题栏目名称'),
        ),
        migrations.AddField(
            model_name='ariticlepost',
            name='article_tag',
            field=models.ManyToManyField(blank=True, related_name='article_tag', to='article.ArticleTag'),
        ),
    ]
