# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0010_auto_20171227_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='关注日期')),
                ('unfollow_time', models.DateTimeField(auto_now=True, verbose_name='取关日期')),
                ('follow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follow', to=settings.AUTH_USER_MODEL, verbose_name='用户关注的其他用户')),
            ],
            options={
                'ordering': ('-follow_time',),
            },
        ),
    ]
