# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_followuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuser',
            name='follow_flag',
            field=models.BooleanField(default=False),
        ),
    ]
