# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_followuser_follow_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followuser',
            name='follow_user',
        ),
        migrations.DeleteModel(
            name='FollowUser',
        ),
    ]
