# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20180102_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ariticlepost',
            options={'ordering': ('-updated',), 'verbose_name': '问题主题内容管理', 'verbose_name_plural': '问题主题内容管理'},
        ),
        migrations.AlterModelOptions(
            name='articletag',
            options={'verbose_name': '问题标签管理', 'verbose_name_plural': '问题标签管理'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': '问题答案管理', 'verbose_name_plural': '问题答案管理'},
        ),
        migrations.AlterField(
            model_name='ariticlepost',
            name='article_tag',
            field=models.ManyToManyField(blank=True, related_name='article_tag', to='article.ArticleTag', verbose_name='问题标签'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='答案的内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentator',
            field=models.CharField(max_length=90, verbose_name='回答问题的人'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='答案创建时间'),
        ),
    ]
